### PR TITLE
Fix grammar issue

### PR DESCRIPTION
**Pull request by amyghuang**

### CODE REVIEW

**Comment by cew821** [comment]
Thanks for the suggestion! However, I think "are" is correct because it refers to the tasks (plural) instead of a single task.

**Comment by amyghuang** [comment]
I understand why it feels like that's correct, but it's actually wrong. A good way to look at it would be to rearrange the sentence as a statement. You wouldn't say "The user are trying to accomplish what primary tasks," you would say "The user is trying to accomplish what primary tasks." In other words, "tasks" is the object of the verb, not the subject.

**Comment by kimballce** [comment]
@amyghuang is correct. The sentence should either read "What primary tasks is the user trying to accomplish?" or "What primary tasks are the users trying to accomplish?" but in either case the verb must agree with "user(s)," which is the subject.

**Comment by cew821** [comment]
Hmm! I have learned something new. Could you re-submit this as "What primary tasks are the users trying to accomplish?"  I believe that would read more easily to folks like me.

cc @nicoleslaw for input.

**Comment by nicoleslaw** [comment]
You could also recast the sentence to avoid the issue (e.g., What is the user trying to accomplish?).

**Comment by amyghuang** [comment]
I think @nicoleslaw's suggestion is the better solution. I will close this issue and resubmit with that phrasing.

**Comment by cew821** [comment]
Thank you!

**Pull request closed without merging**
